services:
  - type: web
    name: jors-cosca-backend
    runtime: node
    rootDir: .
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
